Add functionality to check if PR is closed
EternalCodeTeam/DiscordOfficer pull request #115
Opened 2023-09-03 15:07 UTC by vLuckyyy

2023-09-03 15:25 UTC, Osnixer approved these changes

2023-09-03 19:04 UTC, Hyd3r1 approved these changes

2023-09-03 19:23 UTC, Rollczi commented on src/test/java/com/eternalcode/discordapp/review/GitHubReviewUtilTest.java
> +        this.assertPullRequestUrl("https://github.com/user/repo/pull/123", "user", "repo", 123);
W metodach assertowych nie dodajemy bezpośredniej deklaracji this, static itd

2023-09-03 19:23 UTC, Rollczi commented on src/test/java/com/eternalcode/discordapp/review/GitHubReviewUtilTest.java
>      void testIsPullRequestUrl() {
To fajne miejsce na dynamiczne testy

2023-09-06 17:57 UTC, Rollczi requested changes

2023-09-06 17:57 UTC, Rollczi commented on src/test/java/com/eternalcode/discordapp/review/GitHubReviewUtilTest.java
> +    Collection<DynamicTest> testIsPullRequestTitleValid() {
takie dla valid

return Stream.of("GH-123 This is a valid title", "GH-123 Another valid title")
.map(title -> dynamicTest("Valid Title: " + title, () -> assertTrue(GitHubReviewUtil.isPullRequestTitleValid(title))))

podobnie dla invalid

2023-09-07 04:28 UTC, Rollczi approved these changes

2023-09-07 16:17 UTC, merged