Fix working of voice experience system.
EternalCodeTeam/DiscordOfficer pull request #136
Opened 2023-11-04 00:53 UTC by vLuckyyy

Fixes #133

2023-11-04 00:57 UTC, Osnixer approved these changes
Looks nice!

2023-11-04 08:49 UTC, imDMK approved these changes

2023-11-04 08:49 UTC, imDMK commented on src/main/java/com/eternalcode/discordapp/leveling/experience/voice/ExperienceLeaveVoiceController.java
> +        this.experienceVoiceActivityData.usersOnVoiceChannel.remove(event.getMember().getIdLong());
```suggestion
        this.experienceVoiceActivityData.usersOnVoiceChannel.remove(userId);
```

2023-11-04 17:55 UTC, Hyd3r1 requested changes
Only codestyle problem mentioned by DMK, all other looks great! :D

2023-11-04 18:16 UTC, Jakubk15 approved these changes

2023-11-06 17:51 UTC, Hyd3r1 approved these changes

2023-11-06 17:51 UTC, merged