Add minecraft server info command
EternalCodeTeam/DiscordOfficer pull request #68
Opened 2023-02-23 16:48 UTC by vLuckyyy

![image](https://user-images.githubusercontent.com/65517973/220974192-a9fd9fa7-f3fe-4249-ba24-4b0b2f623f16.png)

2023-02-23 18:05 UTC, Jakubk15 approved these changes
Jest ok, dodaj jeszcze `this`-y przy rejestrowaniu komend, wspomniałem o tym w innym PR.

2023-02-23 18:05 UTC, Jakubk15 commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +                new OptionData(OptionType.STRING, "domain", "The domain of the Minecraft server")
```suggestion
                new OptionData(OptionType.STRING, "address", "The domain/IP address of the Minecraft server")
```

2023-02-23 18:05 UTC, Jakubk15 commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +            event.reply("❌ The server is offline!")
```suggestion
            event.reply("❌ The provided server is offline!")
```

2023-02-25 19:47 UTC, eripe14 requested changes
Można dodać checkStyle

2023-02-25 19:47 UTC, eripe14 commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +        JsonObject response = JsonParser.parseString(this.sendApiRequest(domain)).getAsJsonObject();
upo chyba, nie po co wysyłasz dwa razy tą metodę `sendApiRequest`? Proponuję zrobić to tak:

```
String request = this.sendApiRequest(domain);

JsonObject response = JsonParser.parseString(request).getAsJsonObject();
```

2023-02-28 06:13 UTC, Jakubk15 approved these changes

2023-02-28 06:13 UTC, Jakubk15 approved these changes

2023-02-28 14:55 UTC, eripe14 approved these changes

2023-02-28 18:28 UTC, Hyd3r1 requested changes

2023-02-28 18:28 UTC, Hyd3r1 commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +                .addField("MOTD", motdCleanLine1 + "\n" + motdCleanLine2, false)
Co do MOTD to można to wrzucić do arraya (jako stringi) i automatycznie wrzucać `\n` 

Example:
```
String[] motd = {"My super server", "EternalCode.pl"};
String.join("\n", motd)
```

2023-03-01 17:01 UTC, Hyd3r1 requested changes

2023-03-01 17:01 UTC, Hyd3r1 commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +        String[] motd = { motdClean.get(0).getAsString(), motdClean.get(1).getAsString() };
GSON nie umożliwia czasem pobranie całej listy jako listy z stringami? 
```
Gson gson = new Gson(); 
String[] motd = gson.fromJson(motdClean, String[].class)
```

2023-03-02 10:20 UTC, Osnixer requested changes

2023-03-02 10:20 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +import java.awt.*;
A co to za nie ładny zapach import

2023-03-02 10:20 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +        if (!response.get("online").getAsBoolean()) {
Można było by to w local variable wrzucić

2023-03-02 21:46 UTC, Hyd3r1 requested changes

2023-03-02 21:46 UTC, Hyd3r1 commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +        String[] motd = { motdClean.get(0).getAsString(), motdClean.get(1).getAsString() };
Reported problem by me, is not solved, why u mark it as solved?

2023-03-03 17:50 UTC, Rollczi requested changes

2023-03-03 17:50 UTC, Rollczi commented on src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
> +        Gson gson = new Gson();
To daj do zmiennej statycznej finalnej

2023-03-03 17:59 UTC, Rollczi approved these changes

2023-03-04 08:54 UTC, merged