Leveling system
EternalCodeTeam/DiscordOfficer pull request #91
Opened 2023-06-18 20:21 UTC by Hyd3r1

2023-07-28 03:59 UTC, Osnixer requested changes

2023-07-28 03:59 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/DiscordApp.java
>          DatabaseConfig databaseConfig = new DatabaseConfig();
Zmień proszę wszystkie ładowanie configów na takie:

DatabaseConfig databaseConfig = configManager.load(new DatabaseConfig());

2023-07-28 03:59 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/experience/ExperienceRepository.java
> +    CompletableFuture<List<Experience>> findAll();
Niezbyt stabilne, do tego nie widzę nigdzie użycia tej metody?

2023-07-28 03:59 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/leveling/LevelController.java
> +                return null;
nie lepiej zwrócić tutaj 0 czy 1?

2023-07-28 11:25 UTC, Hyd3r1 commented on src/main/java/com/eternalcode/discordapp/DiscordApp.java
>          DatabaseConfig databaseConfig = new DatabaseConfig();
Okey zmienię

2023-07-30 07:19 UTC, Osnixer approved these changes

2023-07-30 15:13 UTC, vLuckyyy approved these changes

2023-07-30 16:35 UTC, merged