GH-97 Add experience and level rankings
EternalCodeTeam/DiscordOfficer pull request #97
Opened 2023-07-30 17:09 UTC by Hyd3r1

2023-07-30 17:17 UTC, Jakubk15 commented on src/main/java/com/eternalcode/discordapp/DiscordApp.java
> +                        // Tops
```suggestion
```
Przy okazji posortuj to alfabetycznie

2023-07-30 17:17 UTC, Jakubk15 commented on src/main/java/com/eternalcode/discordapp/experience/ExperienceRepository.java
> +    CompletableFuture<List<Experience>> getTop(int limit);
Możesz dodać offset, jak będziesz chciał np. zrobić przewijane strony

2023-07-30 17:17 UTC, Jakubk15 commented on src/main/java/com/eternalcode/discordapp/experience/ExperienceRepositoryImpl.java
> +
jak wyżej

2023-07-30 17:17 UTC, Jakubk15 commented on src/main/java/com/eternalcode/discordapp/leveling/command/Top10LevelCommand.java
> +public class Top10LevelCommand extends SlashCommand {
Ja bym to w sumie zgeneralizował, może na 1 stronie faktycznie byłoby top 10, a potem można byłoby za pomocą buttonów to przewijać jakoś

2023-07-30 20:10 UTC, Osnixer requested changes

2023-07-30 20:10 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/experience/command/Top10ExperienceCommand.java
>                  .setTitle("Top 10 users in experience ranking")
ino pa polish albo config pod to daj

2023-07-30 20:11 UTC, Hyd3r1 commented on src/main/java/com/eternalcode/discordapp/experience/command/Top10ExperienceCommand.java
>                  .setTitle("Top 10 users in experience ranking")
Czyli ile pobrać ma to dać pod config?

2023-08-06 15:32 UTC, vLuckyyy approved these changes

2023-08-06 20:20 UTC, merged