Add an option that automatically assigns forum tags; in the first mes…
EternalCodeTeam/DiscordOfficer pull request #99
Opened 2023-08-17 01:30 UTC by vLuckyyy

…sage of the thread, include the title.

2023-08-17 01:55 UTC, Osnixer approved these changes

2023-08-17 01:55 UTC, Osnixer commented on src/main/java/com/eternalcode/discordapp/review/GitHubReviewService.java
> +        } catch (IOException exception) {
WHY?

2023-08-17 01:56 UTC, vLuckyyy commented on src/main/java/com/eternalcode/discordapp/review/GitHubReviewService.java
> +        } catch (IOException exception) {
Fixed, czysta instalacja intelki.

2023-08-17 06:49 UTC, Jakubk15 approved these changes
Jak dla mnie to chyba powinno być na odwrót, właśnie jako title powinien być pull request title, a w wiadomości link

2023-08-17 11:21 UTC, Hyd3r1 requested changes
Według mnie tytuł powinien być friendly, o to chodziło w Issue, użyj datafile do zapisywania URL: ID co ułatwi działanie na tych kanałach.

2023-08-17 11:57 UTC, vLuckyyy commented
> Jak dla mnie to chyba powinno być na odwrót, właśnie jako title powinien być pull request title, a w wiadomości link

Rozmawialiśmy o tym już kilka razy... TITLE wątku sprawuje gunkcje informacyjna i odniesienie do dalszych działań w systemie, bez tego system nie zadziała, zmiana tego była by czasochłonna i bez sensu na to tracić czas.

2023-08-17 11:58 UTC, vLuckyyy commented
> Według mnie tytuł powinien być friendly, o to chodziło w Issue, użyj datafile do zapisywania URL: ID co ułatwi działanie na tych kanałach.

https://github.com/EternalCodeTeam/DiscordOfficer/pull/99#issuecomment-1682157180

2023-08-18 06:02 UTC, Hyd3r1 approved these changes

2023-08-19 14:42 UTC, merged